name: My GitHub Metrics
on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Generate Base Metrics
        uses: lowlighter/metrics@latest
        with:
          user: anganba
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.base.svg
          base: "header, activity, community, metadata"
          theme: dracula
          
      - name: Generate Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          user: anganba
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.isocalendar.svg
          base: "" 
          theme: dracula
          plugin_isocalendar: yes
          
      - name: Generate Languages
        # This step now ONLY generates languages
        uses: lowlighter/metrics@latest
        with:
          user: anganba
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.languages.svg
          base: "" 
          theme: dracula
          plugin_languages: yes
          plugin_languages_details: "bytes-size, percentage"
          
      - name: Generate Habits
        # This step now ONLY generates habits
        uses: lowlighter/metrics@latest
        with:
          user: anganba
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.habits.svg
          base: "" 
          theme: dracula
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: "true" 
          plugin_habits_lines: 4
